[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/r-xue/casa_proc/blob/master/demo/test_casaproc.ipynb)

## Example BX610: perform model fitting using method='amoeba'

In [24]:
import sys
import glob
import os
import io
import logging
from pprint import pprint

print(sys.version)

import socket 
if  'hypersion' or 'mini' in socket.gethostname() :
    os.chdir('/Users/Rui/Dropbox/Worklib/projects/GMaKE/examples/output/')
print(socket.gethostname())
print(os.getcwd())

import gmake
print(gmake.__version__)
print(gmake.__email__)
print(gmake.__demo__)

inpfile=gmake.__demo__+'/../examples/inpfile/bx610_b6c3_uv_ab.inp'
logfile=''

print('>'*40)
#gmake.logger_config()
#gmake.logger_status()
#import pprint
#pprint.pprint(logging.Logger.manager.loggerDict) 
gmake.logger_config()
inp_dct=gmake.read_inp(inpfile)
inp_dct=gmake.inp_validate(inp_dct)
outdir=inp_dct['general']['outdir']
gmake.logger_config(logfile=outdir+'/gmake.log',loglevel='DEBUG',logfilelevel='DEBUG')
gmake.logger_status()


3.7.5 (default, Oct 19 2019, 11:15:26) 
[Clang 11.0.0 (clang-1100.0.33.8)]
hyperion
/Users/Rui/Dropbox/Worklib/projects/GMaKE/examples/output
0.2.dev1
rx.astro@gmail.com
/Users/Rui/Dropbox/Worklib/projects/GMaKE/gmake
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
**********exe read_inp()**************
<Logger gmake (DEBUG)>
[<FileHandler /Users/Rui/Dropbox/Worklib/projects/GMaKE/examples/output/bx610_b6c3_uv_ab/gmake.log (DEBUG)>, <StreamHandler stderr (DEBUG)>]


In [2]:
dat_dct=gmake.read_data(inp_dct,fill_mask=True,fill_error=True)

read data (may take some time..)

Read: ../data/bx610/alma/2015.1.00250.S/bb2.ms

data@../data/bx610/alma/2015.1.00250.S/bb2.ms                (56354, 238)         102 MiB             
uvw@../data/bx610/alma/2015.1.00250.S/bb2.ms                 (56354, 3)           661 KiB             
weight@../data/bx610/alma/2015.1.00250.S/bb2.ms              (56354,)             220 KiB             161.43835
chanfreq@../data/bx610/alma/2015.1.00250.S/bb2.ms            (238,)     250752859438.0543 Hz 252604264234.0391 Hz
chanwidth@../data/bx610/alma/2015.1.00250.S/bb2.ms           (238,)     7811834.5822 Hz 7811834.5822 Hz
phasecenter@../data/bx610/alma/2015.1.00250.S/bb2.ms         23h46m09.44s  12d49m19.3s
data flagging fraction: 0.0

Read: ../data/bx610/alma/2015.1.00250.S/bb3.ms

data@../data/bx610/alma/2015.1.00250.S/bb3.ms                (53466, 238)          97 MiB             
uvw@../data/bx610/alma/2015.1.00250.S/bb3.ms                 (53466, 3)           627 KiB             
weight@../da

In [3]:
#
#mod_dct=gmake.inp2mod(inp_dct)
#gmake.pprint(mod_dct)
#gmake.model_vrot(mod_dct)
#gmake.pprint(mod_dct)
#gmake.model_vrot_plot(mod_dct['co76'])

In [66]:
inp_dct=gmake.read_inp(inpfile)
inp_dct=gmake.inp_validate(inp_dct)
mod_dct=gmake.inp2mod(inp_dct)
gmake.model_vrot(mod_dct)
#mod_dct['co76']
fit_dct=gmake.fit_setup(inp_dct,dat_dct)
gmake.fit_iterate(fit_dct,inp_dct,dat_dct)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
optimizer: amoeba
optimizing parameters:
----------------------------------------------------------------------------------------------------
index    name    unit    start    lo_limit    up_limit    scale
 0   disk_sd@diskdyn   solMass / pc2        5000.00     (    100.00    ,    50000.00    )   45000.00    
 1   xypos.ra@basics   deg                356.5393258   (  356.5387703 ,   356.5398814  )   0.0005556   
 2   xypos.dec@basics  deg                12.8220182    (  12.8214626  ,   12.8225738   )   0.0005556   
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ndim:    3
outdir:  bx610_b6c3_uv_ab


**********exe read_inp()**************
/Users/Rui/Library/Python/3.7/lib/python/site-packages/galpy/potential/RazorThinExponentialDiskPotential.py:128: RuntimeWarning: invalid value encountered in multiply
  return -2.*nu.pi*y*(special.i0(y)*special.k0(y)-special.i1(y)*special.k1(y))



one trial                                          : 0.88414  seconds
ndata->26249868.0
chisq->66853646.75246938
--- save to: bx610_b6c3_uv_ab/fit.h5
 
Running AMOEBA...
>>bx610_b6c3_uv_ab/amoeba_chain.h5
 


/Users/Rui/Library/Python/3.7/lib/python/site-packages/hickle/hickle.py:403: SerializedWarning: <class 'astropy.units.core.CompositeUnit'> type not understood, data have been serialized
  SerializedWarning)

/Users/Rui/Library/Python/3.7/lib/python/site-packages/hickle/hickle.py:403: SerializedWarning: <class 'astropy.units.core.Unit'> type not understood, data have been serialized
  SerializedWarning)

[5000.          356.53932583   12.82201819]
[5.00000000e+04 3.56539326e+02 1.28220182e+01]
[5000.          356.53988139   12.82201819]
[5000.          356.53932583   12.82257375]


     0   66853649   66870628


[3.50000000e+04 3.56538770e+02 1.28223886e+01]


     1   66853649   66869743


[5.00000000e+04 3.56538955e+02 1.28217096e+01]
[1.75000000e+04 3.56539233e+02 1.28223577e+01]
[2.75000000e+04 3.56539326e+02 1.28220182e+01]
[2.00000000e+04 3.56539048e+02 1.28222034e+01]
[5000.          356.53932583   12.82229597]


     6   66853649   66882991


[3.00000000e+04 3.56539141e+02 1.28218639e+01]


     7   66853649   66882148


[2.16666667e+04 3.56539480e+02 1.28217301e+01]


     8   66853649   66882105


[6111.11111111  356.5396139    12.82198047]
[2.40277778e+04 3.56539259e+02 1.28218930e+01]


    10   66853649   66881657


[1.60185185e+04 3.56539127e+02 1.28222228e+01]
[1.74305556e+04 3.56539215e+02 1.28220996e+01]


    12   66853649   66879173


[2.02546296e+04 3.56539392e+02 1.28218533e+01]
[1.81365741e+04 3.56539259e+02 1.28220381e+01]


    14   66853649   66879076


[9729.9382716   356.53934841   12.82215661]
[2.04533179e+04 3.56539281e+02 1.28219589e+01]


    16   66853649   66870171


[1.33043981e+04 3.56539326e+02 1.28220907e+01]
[1.86660880e+04 3.56539293e+02 1.28219919e+01]


    18   66853649   66870062


[1.59741512e+04 3.56539370e+02 1.28219808e+01]
[1.65147569e+04 3.56539342e+02 1.28219951e+01]


    20   66853649   66862095


[1.40104167e+04 3.56539370e+02 1.28220291e+01]
[1.75021701e+04 3.56539312e+02 1.28220012e+01]


    22   66853649   66859039


[1.68200231e+04 3.56539300e+02 1.28220299e+01]
[1.67437066e+04 3.56539311e+02 1.28220212e+01]


    24   66853649   66857247


[1.53269676e+04 3.56539330e+02 1.28220372e+01]
[1.58707682e+04 3.56539325e+02 1.28220282e+01]


    26   66853649   66856159


[1.55034722e+04 3.56539341e+02 1.28220218e+01]
[1.58135308e+04 3.56539333e+02 1.28220217e+01]


    28   66853649   66855408


[100.         356.53933025  12.82202721]


    29   66853649   66855344


[100.         356.5393343   12.82201651]


    30   66853649   66855174


[100.         356.53932713  12.82201958]


    31   66853649   66854914


[3366.66666667  356.53932793   12.82200898]


    32   66853649   66854882


[5544.44444444  356.53931963   12.82201467]


    33   66853649   66854454


[9174.07407407  356.5393218    12.82200831]
[2368.51851852  356.5393258    12.82201677]


    35   66853428   66854000


[1612.34567901  356.53933341   12.82201463]


    36   66853428   66853995


[2620.57613169  356.53932876   12.82202408]


    37   66853428   66853918


[5047.05075446  356.53932019   12.82202473]
[2471.02194787  356.5393301    12.82201715]


    39   66853428   66853649


[100.         356.53933061  12.82202047]
[3743.35276635  356.53932703   12.82201876]


    41   66853428   66853607


[3101.35269014  356.53932652   12.82201104]
[2740.7702713   356.5393282    12.82202082]


    43   66853428   66853531


[3430.73908957  356.53932392   12.82202041]


    44   66853428   66853497


[1949.99915325  356.53932492   12.8220199 ]
[3295.01436307  356.5393265    12.82201905]


    46   66853428   66853482


[2172.12967902  356.53932975   12.82201734]
[3116.08673693  356.53932538   12.82201964]


    48   66853428   66853461


[3112.30947438  356.53932358   12.82201615]
[2833.65507207  356.53932705   12.82201965]


    50   66853428   66853449


[2250.49252194  356.53932565   12.82201833]
[1728.23160138  356.53932522   12.82201797]


    52   66853404   66853439


[1852.35733809  356.53932695   12.82201685]
[2800.15438722  356.53932577   12.82201895]


    54   66853404   66853433


[2112.45521305  356.53932443   12.82201637]
[2653.35510732  356.53932639   12.82201883]


    56   66853404   66853428


[2767.4828258   356.53932608   12.82202064]
[2468.25959534  356.53932587   12.82201773]


    58   66853404   66853426


[2114.58376251  356.53932617   12.82201765]
[2285.97641869  356.53932607   12.82201797]


    60   66853404   66853413


[2628.76173104  356.53932587   12.82201862]
[2800.15438722  356.53932577   12.82201895]


    62   66853400   66853412


[2553.4799782   356.53932607   12.82201945]
[2532.17488248  356.53932602   12.82201902]


    64   66853400   66853411


[2489.56469105  356.53932592   12.82201816]
[2521.52233463  356.539326     12.82201881]


    66   66853400   66853407


[2280.49595109  356.53932528   12.82201834]
[2560.14031826  356.53932612   12.82201871]


    68   66853400   66853404


[2889.79040068  356.53932634   12.8220191 ]
[2410.31699163  356.53932582   12.82201852]


    70   66853398   66853402


[2544.62369266  356.53932588   12.82201843]
[2527.29767413  356.53932597   12.82201871]
[2485.22865494  356.53932597   12.82201862]
[2465.91966313  356.53932591   12.82201867]
[2519.53936134  356.53932585   12.82201857]


    75   66853398   66853403


[2445.28868912  356.53932575   12.82201856]
[2475.24366349  356.53932591   12.8220186 ]
[2447.77282329  356.53932589   12.82201857]
[2438.11832738  356.53932586   12.82201859]
[2464.92817648  356.53932583   12.82201855]


    80   66853398   66853409


[2427.80284037  356.53932578   12.82201854]
[2442.78032756  356.53932587   12.82201856]


    82   66853398   66853409


[2440.5653364   356.53932582   12.82201849]
[2438.73007963  356.53932585   12.82201857]
[2426.54865959  356.53932584   12.82201854]
[2424.2176595   356.53932584   12.82201856]
[2437.62258405  356.53932583   12.82201853]


    87   66853398   66853409


[2403.09962309  356.53932584   12.82201855]


    88   66853398   66853404


[2398.54085656  356.53932583   12.82201854]
[2419.54670883  356.53932584   12.82201854]
[2418.43282561  356.53932583   12.82201853]
[2417.26732556  356.53932583   12.82201854]
[2406.70830736  356.53932583   12.82201853]


    93   66853398   66853408


[2404.42892409  356.53932582   12.82201853]
[2407.92989947  356.53932583   12.82201853]
[2407.37295786  356.53932582   12.82201853]
[2413.7921586   356.53932583   12.82201853]
[2408.51264949  356.53932583   12.82201853]


    98   66853398   66853413


[2414.37490862  356.53932583   12.82201853]


    99   66853398   66853410


[2417.14338973  356.53932582   12.82201852]


   100   66853398   66853409
--- save to: bx610_b6c3_uv_ab/amoeba_chain.h5


In [68]:
#from hickle import SerializedWarning
gmake.fit_analyze(inpfile,export=True)
#print(fit_dct['p_scale'])

--- save to: bx610_b6c3_uv_ab/fit.h5
Check optimized parameters:
 0   disk_sd@diskdyn   =    2410.32     <-    5000.00     (    100.00    ,    50000.00    )
 1   xypos.ra@basics   =  356.5393258   <-  356.5393258   (  356.5387703 ,   356.5398814  )
 2   xypos.dec@basics  =  12.8220185    <-  12.8220182    (  12.8214626  ,   12.8225738   )


**********exe read_inp()**************
/Users/Rui/Library/Python/3.7/lib/python/site-packages/hickle/hickle.py:403: SerializedWarning: <class 'astropy.units.core.CompositeUnit'> type not understood, data have been serialized
  SerializedWarning)

/Users/Rui/Library/Python/3.7/lib/python/site-packages/hickle/hickle.py:403: SerializedWarning: <class 'astropy.units.core.Unit'> type not understood, data have been serialized
  SerializedWarning)



analyzing outfolder:bx610_b6c3_uv_ab
plotting...bx610_b6c3_uv_ab/iteration.pdf


/Users/Rui/Library/Python/3.7/lib/python/site-packages/galpy/potential/RazorThinExponentialDiskPotential.py:128: RuntimeWarning: invalid value encountered in multiply
  return -2.*nu.pi*y*(special.i0(y)*special.k0(y)-special.i1(y)*special.k1(y))



export the model set:              bx610_b6c3_uv_ab/model_0              (may take some time..)
 
-->data_b6c3_bb2.ms
 
imod2d@../data/bx610/alma/2015.1.00250.S/bb2.ms
write reference model image: 
    imod2d@../data/bx610/alma/2015.1.00250.S/bb2.ms to bx610_b6c3_uv_ab/model_0/imod2d_b6c3_bb2.fits
imod3d@../data/bx610/alma/2015.1.00250.S/bb2.ms
write reference model image: 
    imod3d@../data/bx610/alma/2015.1.00250.S/bb2.ms to bx610_b6c3_uv_ab/model_0/imod3d_b6c3_bb2.fits
pbeam@../data/bx610/alma/2015.1.00250.S/bb2.ms
write reference model image: 
    pbeam@../data/bx610/alma/2015.1.00250.S/bb2.ms to bx610_b6c3_uv_ab/model_0/pbeam_b6c3_bb2.fits
write reference model profile: 
    imod3d_prof@co76@../data/bx610/alma/2015.1.00250.S/bb2.ms to bx610_b6c3_uv_ab/model_0/imodrp_co76_b6c3_bb2.fits


bx610_b6c3_uv_ab/model_0
['cube.', 'mfs.', 'cube3.']
[('../data/bx610/alma/2015.1.00250.S/', 'b6c3_')]


write reference model profile: 
    imod3d_prof@ci21@../data/bx610/alma/2015.1.00250.S/bb2.ms to bx610_b6c3_uv_ab/model_0/imodrp_ci21_b6c3_bb2.fits
copy ms container: 
    ../data/bx610/alma/2015.1.00250.S/bb2.ms  to  bx610_b6c3_uv_ab/model_0/model_b6c3_bb2.ms
write ms column: 
    uvmodel@../data/bx610/alma/2015.1.00250.S/bb2.ms to data@bx610_b6c3_uv_ab/model_0/model_b6c3_bb2.ms
create symlink:
    /Users/Rui/Dropbox/Worklib/projects/GMaKE/examples/data/bx610/alma/2015.1.00250.S/bb2.ms  to  bx610_b6c3_uv_ab/model_0/data_b6c3_bb2.ms
 
-->data_b6c3_bb3.ms
 
imod2d@../data/bx610/alma/2015.1.00250.S/bb3.ms
write reference model image: 
    imod2d@../data/bx610/alma/2015.1.00250.S/bb3.ms to bx610_b6c3_uv_ab/model_0/imod2d_b6c3_bb3.fits
imod3d@../data/bx610/alma/2015.1.00250.S/bb3.ms
write reference model image: 
    imod3d@../data/bx610/alma/2015.1.00250.S/bb3.ms to bx610_b6c3_uv_ab/model_0/imod3d_b6c3_bb3.fits
pbeam@../data/bx610/alma/2015.1.00250.S/bb3.ms
write reference model image: 
  

/Users/Rui/Library/Python/3.7/lib/python/site-packages/hickle/hickle.py:403: SerializedWarning: <class 'astropy.io.fits.header.Header'> type not understood, data have been serialized
  SerializedWarning)



--- save to: bx610_b6c3_uv_ab/model_0/models.h5
model_0: 
{'chisq': 66853638.49608389,
 'lnprob': 10223010.930221781,
 'ndata': 26249868.0,
 'npar': 3}
export the model set:              bx610_b6c3_uv_ab/model_1              (may take some time..)
 
-->data_b6c3_bb2.ms
 
imod2d@../data/bx610/alma/2015.1.00250.S/bb2.ms
write reference model image: 
    imod2d@../data/bx610/alma/2015.1.00250.S/bb2.ms to bx610_b6c3_uv_ab/model_1/imod2d_b6c3_bb2.fits
imod3d@../data/bx610/alma/2015.1.00250.S/bb2.ms
write reference model image: 
    imod3d@../data/bx610/alma/2015.1.00250.S/bb2.ms to bx610_b6c3_uv_ab/model_1/imod3d_b6c3_bb2.fits
pbeam@../data/bx610/alma/2015.1.00250.S/bb2.ms
write reference model image: 
    pbeam@../data/bx610/alma/2015.1.00250.S/bb2.ms to bx610_b6c3_uv_ab/model_1/pbeam_b6c3_bb2.fits
write reference model profile: 
    imod3d_prof@co76@../data/bx610/alma/2015.1.00250.S/bb2.ms to bx610_b6c3_uv_ab/model_1/imodrp_co76_b6c3_bb2.fits
write reference model profile: 


bx610_b6c3_uv_ab/model_1
['cube.', 'mfs.', 'cube3.']
[('../data/bx610/alma/2015.1.00250.S/', 'b6c3_')]


    imod3d_prof@ci21@../data/bx610/alma/2015.1.00250.S/bb2.ms to bx610_b6c3_uv_ab/model_1/imodrp_ci21_b6c3_bb2.fits
copy ms container: 
    ../data/bx610/alma/2015.1.00250.S/bb2.ms  to  bx610_b6c3_uv_ab/model_1/model_b6c3_bb2.ms
write ms column: 
    uvmodel@../data/bx610/alma/2015.1.00250.S/bb2.ms to data@bx610_b6c3_uv_ab/model_1/model_b6c3_bb2.ms
create symlink:
    /Users/Rui/Dropbox/Worklib/projects/GMaKE/examples/data/bx610/alma/2015.1.00250.S/bb2.ms  to  bx610_b6c3_uv_ab/model_1/data_b6c3_bb2.ms
 
-->data_b6c3_bb3.ms
 
imod2d@../data/bx610/alma/2015.1.00250.S/bb3.ms
write reference model image: 
    imod2d@../data/bx610/alma/2015.1.00250.S/bb3.ms to bx610_b6c3_uv_ab/model_1/imod2d_b6c3_bb3.fits
imod3d@../data/bx610/alma/2015.1.00250.S/bb3.ms
write reference model image: 
    imod3d@../data/bx610/alma/2015.1.00250.S/bb3.ms to bx610_b6c3_uv_ab/model_1/imod3d_b6c3_bb3.fits
pbeam@../data/bx610/alma/2015.1.00250.S/bb3.ms
write reference model image: 
    pbeam@../data/bx610/alma/2015.

<Figure size 432x288 with 0 Axes>

In [6]:
0.00027778*3600

1.000008